### ISSUE TITLE
Remove the Low QPS threshold for SGPP

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-resource-controller-k8s#104]
**What would you like to be enhanced**:

Currently, SGPP assignment by design , a low QPS call done VPC Resource Controller when it tries to associate Trunk ENI to Branch.
 
https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/config/loader.go#L29-L30

That is because SGP by costly operation, and this will be lower qps set than any other EC calls.

However, we should consider removing that low QPS call and let the max pod creation threshold be handled by kubernetes.

**Why is the change needed and what use case will it solve**:

There was  customer report that when SGPP was enabled, their deployment scaling took a long time, and they wanted to avoid it

**Comment by bwhaley** [comment]
Folks, any updates on when this will be prioritized? SGFP is effectively unusable in our environment (which is not even that big in terms of AWS customer scale) due to this low limit.
