### ISSUE TITLE
Bug: Cannot use PodSecurityGroups with C7G instances - EKS AMI and VPC CNI support C7G's, but vpc-resource-controller does not

### ISSUE THREAD

**Issue by armenr** [aws/amazon-vpc-resource-controller-k8s#107]
**Describe the Bug**:
C7G instances appear to be supported in EKS - as per these references -->

- https://github.com/aws/amazon-vpc-cni-k8s/commit/59b9e944cfa1cf3a3b079e536f6d6cee7c956720
- https://github.com/aws/amazon-vpc-cni-k8s/commit/1408e0343bbf6091ff9b9fe332f6b197899907de
- https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

Unfortunately, C7G instances do not appear to support PodSecurity Groups. I tried to spin up a cluster and PodSecurity Groups didn't work. I suspect that it's because we're missing c7g instances from this file:

https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go

Could someone confirm? If so, I can try to open a PR.

**Observed Behavior**:

C7G instances in EKS work, but don't work with PodSecurityGroups.

**Expected Behavior**:

I can replace my m6g's with c7g's in terraform, and re-apply my infra & configs, getting back an EKS cluster with node_groups and Pods w/ PodSecurityGroups.

Substitute C7G instances in our current configurations, and operate them normally - with PodSecurityGroups.

**How to reproduce it (as minimally and precisely as possible)**:

- Create EKS cluster
- Configure for C7Gs
- Reuse the same configs & deployments as you would for a working, m6g cluster

**Additional Context**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): EKS 1.22.6
- CNI Version: latest
- OS (Linux/Windows): OSX

**Comment by jayanthvn** [comment]
Yes c7g is not supported yet in VPC resource controller. We will take it up in the next release.

**Comment by haouc** [comment]
@armenr, as Jayanth mentioned, we can add the support in the next release. If you would like to send a PR for this, please feel free to do so.

**Comment by haouc** [comment]
c7g type has been added and tested. we will have this change available to use when the next version is released. I am closing this issue.
