### ISSUE TITLE
Update controller-runtime to 0.9.7

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-resource-controller-k8s#142]
**What would you like to be enhanced**:
Update controller-runtime dependency to 0.9.7

**Why is the change needed and what use case will it solve**:
This change is needed as 0.9.5 exposes high metric cardinality to prometheus: https://github.com/kubernetes-sigs/controller-runtime/issues/1423

**Comment by krishnaindani** [comment]
is this just upgrading dependency? Do we see any breaking code changes? I would like to attempt this

**Comment by jdn5126** [comment]
> is this just upgrading dependency? Do we see any breaking code changes? I would like to attempt this

Yes, this issue is just to upgrade the dependency, and no breaking changes are expected. Thanks!

**Comment by krishnaindani** [comment]
Can I work on this?

**Comment by krishnaindani** [comment]
Thanks, will add a pr for this

**Comment by krishnaindani** [comment]
Have added a pr https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/147. Let me know if any corrections are needed. Thanks

**Comment by jdn5126** [comment]
> Have added a pr #147. Let me know if any corrections are needed. Thanks

Sorry @krishnaindani , we need to wait to merge this until after a release is pulled. I reverted this at #148

**Comment by jdn5126** [comment]
Closing as the version has been updated
