### ISSUE TITLE
Create pod event when VPC Controller is unable to assign Branch ENI to Pod

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-resource-controller-k8s#15]
**What would you like to be enhanced**:
- Emit all error messages associated with creating Branch ENIs to pod event to help users debug and fix the issue easily.
- Emit node events with appropriate error message if the Trunk ENI Creation fails.

**Why is the change needed and what use case will it solve**:
This change will help users resolve configuration issues like missing IAM permissions, PSP blocking VPC Resource Controller to annotate pod with the Branch ENI details.

**Comment by SaranBalaji90** [comment]
I was under the impression we do emit log event as part of fcreate failure and we verified these error messages before GA - https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/provider/branch/provider.go#L341 (is that not the case?)

**Comment by abhipth** [comment]
Yes Balaji, you are right we do emit errors in the event if branch ENI Creation fails. Currently we don't emit event in case the pod annotation (with branch ENI details) fails and also don't annotate the node if the trunk ENI creation fails.
