### ISSUE TITLE
Allow More Than 5 Security Groups When Using Security Groups For Pods

### ISSUE THREAD

**Issue by jrbil** [aws/amazon-vpc-resource-controller-k8s#155]
**What would you like to be enhanced**:

When using the Security Groups For Pods feature the following error is generated when assigning more than 5 Security Groups:

`"The SecurityGroupPolicy \"collibradq-spark\" is invalid: spec.securityGroups.groupIds: Invalid value: 6: spec.securityGroups.groupIds in body should have at most 5 items"`
&nbsp;
The limit is enforced at:
https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/apis/vpcresources/v1beta1/securitygrouppolicy_types.go#L33
&nbsp;
Before the controller can be updated branch ENI support needs to be confirmed.
&nbsp;
**Why is the change needed and what use case will it solve**:

Allow customers to use more than 5 Security Groups.

**Comment by jwtje** [comment]
I second this, when an app needs to use more than 5 external resources this will be limiting.

**Comment by Sefiris** [comment]
Upvoting this, the default is set to 5, but it is adjustable to up to 16 per network interface.

https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups

**Comment by haouc** [comment]
Thanks for submitting the request. I will provide an update here soon.

**Comment by Sefiris** [comment]
@haouc do you by any chance have an update for us?

No pressure, just trying to get an estimate of how and when the security groups for pods becomes usable in most of our scenarios here.

I would attempt a PR myself but my Go expertise is quite lacking to even make sense of the above referenced validators

**Comment by haouc** [comment]
@Sefiris I am working with our team to check if we can safely increase this limitation. From my test at least, I am seeing 16 as a limit on single interface. I need confirm with EC2 and provide an update here. Sorry for the late response.

**Comment by haouc** [comment]
From AWS public doc, the current quota for security groups per network interface is default to 5 and up to 16. I will verify this with our teams and check what we can do. Thanks.

**Comment by prajwalendra** [comment]
@haouc , any update on this?

**Comment by haouc** [comment]
In order to support more than 5 security groups per pod, one solution can be
- create more than one SGP CRD objects
- make sure they use same pod/SA labels (targeting same set of pods) with different names
- you will have more than 5 security groups being added to the interface that associates to your pod
