### ISSUE TITLE
Allow Security Groups to be referenced by Name in Security Group Policies

### ISSUE THREAD

**Issue by abeer91** [aws/amazon-vpc-resource-controller-k8s#158]
**What would you like to be enhanced**:

IIUC, the Security Group Policies, can only contain a security group id today. Can this be extended to support security group names as well?

**Why is the change needed and what use case will it solve**:

In our setup developers have access to security-group-names that help them understand what resources they will have access to (for e.g. allow-foo-service). This makes it easy for developers to attach the appropriate security groups to their deployments. Supporting this use case will enable us in directly using the interface provided by the VPC Resource Controller.

**Comment by haouc** [comment]
Hey @abeer91, thanks for sharing your use case. This sounds similar to this #20 . We will do some research and prioritize the work if it is feasible. I am closing this request for now due to duplication. Please feel free to reopen it if otherwise. Thanks.
