### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-resource-controller-k8s#161]
This is a feature request to fix GitHub workflows and automatically run unit tests against submitted PRs.

**Comment by haouc** [comment]
@jdn5126 thanks for bring this up. We do need to enable these actions as high priority. I will work on this next week. Thanks.

**Comment by haouc** [comment]
@jdn5126 thanks for bring this up. We do need to enable these actions as high priority. I will work on this next week. Thanks.

**Comment by haouc** [comment]
Unit tests has been enabled. We will work to add more checks against PRs. Thanks.
