### ISSUE TITLE
New instance types not supported

### ISSUE THREAD

**Issue by barryrobison** [aws/amazon-vpc-resource-controller-k8s#162]
**What would you like to be enhanced**:

c6in, r6idn, m6idn instances currently do not have the `vpc.amazonaws.com/has-trunk-attached=true` label applied nor trunk ENIs attached. This means pods requiring Security Groups ( via ENABLE_POD_ENI ) can't be scheduled on them.

**Why is the change needed and what use case will it solve**:

Our AutoScaling Groups use *Instance Requirements* and some AZs are only getting c6in instances.

I've also opened https://github.com/aws/amazon-vpc-cni-k8s/issues/2166 on the vpc-cni side. I'm not entirely clear if their is a mutual requirement to support the new types.

**Comment by haouc** [comment]
@barryrobison thanks for submitting this request. We will update the supported types and make them available for the feature with the next release. We are also investigate if it is a good time to implement #98 to avoid use hard-coded support file.

**Comment by haouc** [comment]
c6in, r6idn, and m6idn families have been added and released to all new clusters. The upgrading existing clusters is in process now. I will update here when the global upgrade finishes.

**Comment by haouc** [comment]
All regions have been upgraded. Closing this ticket.

**Comment by essh** [comment]
@haouc are you able to share the version that was upgraded to so that we can update our list of approved instance types to the latest based on the version currently running in the control plane? It may also be beneficial to update https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html as the reference to `limits.go` still links to `1.1.4`.

**Comment by haouc** [comment]
@essh sorry for the out-dated doc. We will update the doc accordingly. You can always check your clusters' `EKS Platform Version` and then check this controller latest deployed version's `EKS Platform Version` at release page, for example, the current latest version v1.2.2 supporting platform versions listed [here](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.2.2). If your clusters' platform version has been updated to the version(s) listed in release note, you can check the supported instance types in `limit.go` file, for example for v1.2.2, please check the file [here](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/release-1.2.2/pkg/aws/vpc/limits.go). We may create a release note for new version(s) that has been deployed to all new clusters, but old clusters may haven't been updated yet. Checking your clusters' platform version before checking the regarding release version's `limit.go` file is always recommended.
I will work with our team to update our doc with the recommendation as well. Thanks.
