### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by cudders** [aws/amazon-vpc-resource-controller-k8s#17]
Hi,

We're investigating using arm64 node groups in EKS and have a lot of windows container workloads.
We'd need an arm64 build, same for vpc-admission-webhook I guess, is this on the roadmap?

Many thanks,
Chris

**Comment by mikestef9** [comment]
We are planning on moving this controller to the Kubernetes control plane for EKS clusters, so it's not a component you will need to manually install there. Adding Arm support is also something we we would like to do though, so will leave this issue open to track this feature request.

**Comment by cudders** [comment]
Perfect, thanks Mike.

**Comment by iusergii** [comment]
@mikestef9 is there any issue we can track for moving controller to control plane?

**Comment by abhipth** [comment]
@iusergii we are tracking it using this issue - https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/4

**Comment by abhipth** [comment]
Windows Support is now available on EKS Control Plane. It is available on EKS Platform versions mentioned in [v1.1.0 release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0)
