### ISSUE TITLE
Update to newer k8s versions (and golang as well!)

### ISSUE THREAD

**Issue by dims** [aws/amazon-vpc-resource-controller-k8s#172]
currently we are using 1.21 k8s in our vendored dependencies:
https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/go.mod#L23-L24

upstream does not guarantee more than a skew of 2, so could we get this update do say 1.25?

while we are at it, please update to newer 1.19.x golang as well please.

thanks,
Dims

**Comment by haouc** [comment]
@dims Thank you for creating this request. We are working on upgrading and testing the dependencies. I will provide updates here.

**Comment by haouc** [comment]
We have upgraded dependencies in the PR #179 . Closing this issue.
