### ISSUE TITLE
Customers using m6in.2xlarge type instances are not able to get the IP address assigned.

### ISSUE THREAD

**Issue by 77-more** [aws/amazon-vpc-resource-controller-k8s#193]
**What would you like to be enhanced**:
Customers using m6in.2xlarge type instances are not able to get the IP address assigned. Since this instance type is released recently, can you please add the instance type to the allow list. 

**Why is the change needed and what use case will it solve**:
Customers looking for high network performance will be looking to use m6in and r6in instance family and if these instances are  not added to the allow list, the pods that land on these instances will get stuck in pending status.

**Comment by haouc** [comment]
@77-more Thanks for submitting the issue. The instance type has been added already (#187) and will be released soon. Per discussion offline, sounds this issue happening for a Windows node. We need reassess why we need to check Windows node from the list.

**Comment by haouc** [comment]
We are planning an effort to support runtime lookup for Windows support. The enhancement will be tracked as #196

**Comment by haouc** [comment]
m6in family has been added and released to all new clusters. The upgrading existing clusters is in process now. I will update when the global upgrade finishes.

**Comment by haouc** [comment]
Since the version supporting this instance types has been deployed to all clusters, closing this issue.
