### ISSUE TITLE
Branch ENI provider emits warning when IPAM is enabled for Windows node

### ISSUE THREAD

**Issue by jiechen0826** [aws/amazon-vpc-resource-controller-k8s#231]
**What would you like to be enhanced**:
Using v1.1.6 image, describing node shows this warning message for Windows node:
  `  Warning  Unsupported         76s (x3 over 3m23s)  vpc-resource-controller  The instance type c5.xlarge is not supported for trunk interface (Security Group for Pods)`

Pods IP allocation works fine and the controller does not actually initialize the branch ENI. It's just that checking `IsInstanceSupported` will emit the warning to Windows node.

**Why is the change needed and what use case will it solve**:
The warning didn't cause any issues, but it would be confusing to users that may lead them to think something is wrong with the controller.

**Comment by haouc** [comment]
Thanks for reporting this issue, @jiechen0826 . This should be an incorrect message being sent to Windows node when trunk ENI provider error out from provisioning Windows resources. We should either not invoking trunk provider for Windows workflow, or not generate event for Windows node. I will make a change soon.

**Comment by haouc** [comment]
The fix has been merged as #232. The next release will include this fix. I am keeping this issue open for visibility till it has been rolled out to all clusters.

**Comment by haouc** [comment]
The rollout has been finished. Closing this ticket.
