### ISSUE TITLE
The Controller panics on SIGSEGV when flags were missing

### ISSUE THREAD

**Issue by haouc** [aws/amazon-vpc-resource-controller-k8s#290]
**Describe the Bug**:

If some flags (such as `--cluster-name` or `--role-arn`) are missing for some reason, the ENI cleaner is failing on SIGSEGV panic)
**Observed Behavior**:
```
{"level":"info","timestamp":"2023-08-11T01:21:18.404Z","logger":"eni cleaner","msg":"starting eni clean up routine"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1b36d5c]

goroutine 52 [running]:
github.com/aws/amazon-vpc-resource-controller-k8s/pkg/aws/ec2/api.(*ENICleaner).cleanUpAvailableENIs(0xc0000e9880)
        /workspace/pkg/aws/ec2/api/eni_cleanup.go:108 +0x45c
github.com/aws/amazon-vpc-resource-controller-k8s/pkg/aws/ec2/api.(*ENICleaner).Start(0xc0000e9880, {0x26083c8?, 0xc00040e730})
        /workspace/pkg/aws/ec2/api/eni_cleanup.go:67 +0xbf
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0xc0005816e0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/manager/runnable_group.go:219 +0xdb
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/manager/runnable_group.go:203 +0x1ad
```
**Expected Behavior**:
The controller should log the missing flag(s) and exit with error code instead of existing on SIGSEGV panic.
**How to reproduce it (as minimally and precisely as possible)**:
Incorrectly providing the flag(s) can reproduce the issue.
**Additional Context**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.26
- CNI Version: 1.12.x
- OS (Linux/Windows): Linux

**Comment by sushrk** [comment]
Synced on this offline earlier; we already check that `cluster-name` is a required parameter in the controller and exit [here](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/f2bd58eeb257624130b56f0545abee6e415262d1/main.go#L185), and if role-arn is empty, we simply assume the EC2 instance role on which controller is running (CPI or node role ARN if running on dataplane), [see](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/ec2/api/wrapper.go#L395).

I also checked few other flags and did not observe this panic. Closing the issue.
