### ISSUE TITLE
Add m7i/m7a to /pkg/aws/vpc/limits.go

### ISSUE THREAD

**Issue by jlyons210** [aws/amazon-vpc-resource-controller-k8s#291]
**What would you like to be enhanced**:
IHAC requesting limits details for the recently GA'ed m7i and m7a instances to [limits.go](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go)

**Why is the change needed and what use case will it solve**:
This is needed to remain current with recently launched instance families.

**Comment by sushrk** [comment]
Thanks for the report, we will update this on the next release.

**Comment by larhauga** [comment]
@sushrk when can we expect this to be supported?

**Comment by sushrk** [comment]
We have merged the changes to add m7i/a instance type. Current ECD to deploy to all clusters is by end of October.

**Comment by chlunde** [comment]
For anyone eagerly waiting for this. I expect this is the event to look for (check a port started the last hour):

```
  Normal  ControllerVersionNotice  22s   vpc-resource-controller  The node is managed by VPC resource controller version v1.3.0
```

https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/293

**Comment by sushrk** [comment]
This is now available with `v1.4.0` release, thanks!

**Comment by chlunde** [comment]
@sushrk didn't the `ControllerVersionNotice` Event from vpc-resource-controller make it to the same release?

A freshly started pod does not have this event:

```
k describe po                       app-x-7798c5c665-25965     | grep vpc-resource-controller
  Normal   SecurityGroupRequested  116s                 vpc-resource-controller  Pod will get the following Security Groups [sg-abcdef]
  Normal   ResourceAllocated       115s                 vpc-resource-controller  Allocated [{"eniId":"eni-abcdef",..."}] to the pod
```

**Comment by chlunde** [comment]
update :man_facepalming: 

check events on a _node_ to check the version number (a node started the last hour):

```
kubectl describe node ...
  Normal   ControllerVersionNotice  110s                 vpc-resource-controller  The node is managed by VPC resource controller version v1.4.0
```

**Comment by sushrk** [comment]
@chlunde that's right. The event is published on the nodes.
