### ISSUE TITLE
Increasing "CoolDownPeriod" time from 30s to 60s

### ISSUE THREAD

**Issue by ssup2** [aws/amazon-vpc-resource-controller-k8s#306]
**What would you like to be enhanced**: Increasing [CoolDownPeriod](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/provider/branch/trunk/trunk.go#L40) time from 30s to 60s

**Why is the change needed and what use case will it solve**: Now vpc-rc use cool down period to propagate changed network rules when deleting branch ENI. But I think cool down period must be higher than 60s. Because linux kernel's default ARP Cache timeout is 60s. This means that when a new pod is created with a IP used by another deleted pod for less than 1 minute. Is there any reason why 30s is used?

**Comment by jayanthvn** [comment]
I think the 30 seconds was used to be inline with AWS VPC CNI cooldown time and that was because kubeproxy takes upto 30 seconds to clean up the endpoints. During this time we don't want any other pod to get the same IP hence we add the IP to cooldown for 30 seconds.

**Comment by haouc** [comment]
We are planning to make a change to be aligned with Linux settings. @sushrk will help fixing this issue. Thanks

**Comment by jdn5126** [comment]
Closing as fixed by https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/342
