### ISSUE TITLE
Support vpc-rc logging options for Amazon EKS Control plane

### ISSUE THREAD

**Issue by ssup2** [aws/amazon-vpc-resource-controller-k8s#307]
**What would you like to be enhanced**: Support vpc-rc logging options for Amazon EKS control plane

**Why is the change needed and what use case will it solve**: vpc-rc runs on EKS control plane. The other components in EKS control plane such as API Server, Controller Manager, Authenticate Server supports logging options. But vpc-rc dosen't support logging options and customer can't find any operations information of vpc-rc.

**Comment by jayanthvn** [comment]
Currently yes this is not supported. Can you please open a request here https://github.com/aws/containers-roadmap
