### ISSUE TITLE
Add r7iz instances to limits.go

### ISSUE THREAD

**Issue by fproske** [aws/amazon-vpc-resource-controller-k8s#308]
I would like to see the r7iz instance type added to [limits.go](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go)

This would allow us to use the new instances in our cluster, which uses of security groups for pods.

**Comment by jdn5126** [comment]
Closing as fixed by https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/316
