### ISSUE TITLE
Support for windows prefix delegation

### ISSUE THREAD

**Issue by sg-stijnchristiaens** [aws/amazon-vpc-resource-controller-k8s#334]
As far as I can see, there currently is no way through this Helm chart to influence the amazon-vpc-cni configmap to include the enable-windows-prefix-delegation setting for the VPC CNI addon. 
Could it be made configurable in the values file of the chart to support it similarly to the enable-windows-ipam and enable-network-policy-controller settings?

**What would you like to be added**:
The ability to influence parameter enable-windows-prefix-delegation in the amazon-vpc-cni ConfigMap
enable-windows-prefix-delegation = "true" or "false"

**Why is this needed**:
It currently is not possible to bootstrap a new EKS cluster with the VPC CNI addon enabled and enable Windows support including Windows Prefix delegation. 
The existing configmap (amazon-vpc-cni) can be altered after initial creation but it should be possible to configure this directly.

**Comment by haouc** [comment]
yeah, currently we don't allow using this through [EKS addons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) configuration. This is not a feature managed by VPC CNI thus as Jeff suggested this will not be included in VPC CNI helm chart. We are working with teams to check if we can support this through EKS addons.

**Comment by haouc** [comment]
We are working on this with other team. I will provide an update here soon.

**Comment by jdn5126** [comment]
Support for configuring Windows Prefix Delegation values from the `amazon-vpc-cni` helm chart and EKS addon has shipped with VPC CNI version v1.16.0
