### ISSUE TITLE
Usage Metrics for branch eni resources

### ISSUE THREAD

**Issue by achevuru** [aws/amazon-vpc-resource-controller-k8s#34]
**What would you like to be enhanced**:
   Currently, VPC resource controller doesn't expose any branch eni usage metrics at an instance/node level and providing them would be very useful for tracking resource usage and to be able to act on it.

**Why is the change needed and what use case will it solve**:
    Having access to resource limits at instance and cluster level will be useful to monitor the limits for resources that VPC resource controller manages and can be used for alerting. Will also be extremely useful for debugging purposes.

**Comment by abhipth** [comment]
Introspection API will be available from [v1.1.0 release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0)
