### ISSUE TITLE
Support RuntimeClasses for Windows Pod Scheduling

### ISSUE THREAD

**Issue by overdrive3000** [aws/amazon-vpc-resource-controller-k8s#35]
**Is your feature request related to a problem? Please describe.**
Kubernetes documentation recommends to use `RuntimeClasses` to [simplify Windows Pod Scheduling](https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#simplifying-with-runtimeclass) however this is not possible when using EKS as the webhook code is just looking for `NodeSelector` configuration in PodSpec.

**Describe the solution you'd like**
Looking in PodSpec in `runtimeClassName` is defined and search for `NodeSelector` config in specified RuntimeClass otherwise look `NodeSelector` in PodSpec.

**Describe alternatives you've considered**

**Additional context**
Take into account that defining different configurations for `NodeSelector` in both PodSpec and RuntimeClass will make Kubernetes scheduler to return an error.

**Comment by sushrk** [comment]
This issue can be closed now as no changes are required on the controller, the runtimeClass `nodeSelector` is automatically merged into pod by the RuntimeClass Admissions Controller https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/585-runtime-class/README.md#runtimeclass-admission-controller

Also see https://github.com/aws/containers-roadmap/issues/1106
