### ISSUE TITLE
Node Validating Webhook for Custom Networking with Security Groups for Pods - fails when Mutating Webhook is present

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-resource-controller-k8s#350]
**Describe the Bug**:
When Custom Networking is configured with Security Groups for Pods, the node validating webhook: https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/webhooks/core/node_update_webhook.go checks that only certain node fields are modified.

When a mutating webhook is configured, the node validating webhook fails despite the mutating webhook not touching the fields that the node validating webhook cares about:
```
{"level":"error","ts":"[REDACTED]","caller":"retry/util.go:51","msg":"Failed to patch node [REDACTED] with label \"vpc.amazonaws.com/eniConfig\": \"eu-west-2c\",error: admission webhook \"vnode.vpc.k8s.aws\" denied the request: aws-node can only update limited fields on the Node Object"}
```

**Expected Behavior**:
The node validating webhook should be able to handle a mutating webhook being configured. Also, we should update the node validating webhook to be aware of `CNINode` instead of the `vpc.amazonaws.com/has-trunk-attached` label.

**How to reproduce it (as minimally and precisely as possible)**:
Configure Custom Networking with Security Groups for Pods. Add a mutating webhook that adds a label to a node.

**Additional Context**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): Any
- CNI Version: Any
- OS (Linux/Windows): Linux

**Comment by haouc** [comment]
Since the webhook only checks requests initialized by aws-node, it is unclear for me why a mutating webhook's request was intercepted by this webhook. Can you check who sent the request?

**Comment by sushrk** [comment]
As per internal discussion, the recommendation here is to upgrade to VPC-CNI v1.15.0 and above, which adds support for CNINode CRD for managing security group for pods feature. 

Closing the issue.
