### ISSUE TITLE
How to recover securitygrouppolicies.vpcresources.k8s.aws CRD in EKS cluster

### ISSUE THREAD

**Issue by bettaps** [aws/amazon-vpc-resource-controller-k8s#358]
Hello,
I accidentally deleted the default CRDs securitygrouppolicies.vpcresources.k8s.aws, cninodes.vpcresources.k8s.aws and eniconfigs.crd.k8s.amazonaws.com in an EKS cluster. How can i recover them ?

Thanks!

**Comment by haouc** [comment]
@bettaps you can re-install securitygrouppolicies and cninodes from https://github.com/aws/amazon-vpc-resource-controller-k8s/tree/master/config/crd/bases. You can reinstall eniconfigs from https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L2-L22

Also EKS platform version updates also check securitygrouppolicies and cninodes installation. If they are missing, they will be installed.
