### ISSUE TITLE
Set role session name to easier track down who's doing what in cloudtrail

### ISSUE THREAD

**Issue by chlunde** [aws/amazon-vpc-resource-controller-k8s#37]
**What would you like to be enhanced**:

Consider setting role session name on the AWS SDK session.

**Why is the change needed and what use case will it solve**:

To allow easier audit and understanding what happens, and easier track down when the VPC resource controller policy is missing.
The current role session name is unix nano timestamp.

**Comment by chlunde** [comment]
@abhipth thanks!

**Comment by abhipth** [comment]
Changes have been released and are available on EKS Platform versions mentioned in the [v1.1.0 release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0)
