### ISSUE TITLE
Gracefully handle failures in the controller in case of a configuration error with custom networking

### ISSUE THREAD

**Issue by jaydeokar** [aws/amazon-vpc-resource-controller-k8s#382]
**Describe the Bug**: 
SGPP used with Custom Networking. VPC resource controller should fail gracefully when there is a configuration issue for Custom networking.

**Observed Behavior**:

```
 W0305      10 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1alpha1.ENIConfig: json: cannot unmarshal array into Go struct field ENIConfigSpec.items.spec.subnet of type string
2024-03-05 17:35:21.519000+00:00 E0305 17:35:20.619922      10 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.ENIConfig: failed to list *v1alpha1.ENIConfig: json: cannot unmarshal array into Go struct field ENIConfigSpec.items.spec.subnet of type string
 {"level":"error","timestamp":"2024-03-05T17:35:21.423Z","logger":"node manager","msg":"healthz check has a preset timeout to fail no responding probing","TimeoutInSecond":10,"error":"healthz check failed due to timeout","stacktrace":"github.com/aws/amazon-vpc-resource-controller-k8s/pkg/healthz.PingWithTimeout\n\t/workspace/pkg/healthz/healthz.go:93\ngithub.com/aws/amazon-vpc-resource-controller-k8s/pkg/node/manager.NewNodeManager.(*manager).check.func1\n\t/workspace/pkg/node/manager/manager.go:564\nsigs.k8s.io/controller-runtime/pkg/healthz.(*Handler).serveAggregated\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/healthz/healthz.go:59\nsigs.k8s.io/controller-runtime/pkg/healthz.(*Handler).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/healthz/healthz.go:148\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).addHealthProbeServer.StripPrefix.func3\n\t/usr/local/go/src/net/http/server.go:2179\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2136\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2514\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"}
```

**Expected Behavior**:

The controller should give out the error as a warning message in node events and should not restart continuously till the configuration is fixed

**How to reproduce it (as minimally and precisely as possible)**:
Create a EKS cluster, Enable SGPP and Custom Networking. In ENI config, instead of an array for subnet fields, specify a string.

**Additional Context**:
N/A

**Environment**: 
- Kubernetes version (use `kubectl version`): EKS version shouldn't matter
- CNI Version: Version shouldn't matter (v1.16.4)
- OS (Linux/Windows): Linux

**Comment by haouc** [comment]
Agree. We should handle this kind of customer induced errors gracefully.

**Comment by haouc** [comment]
I think this should be handled at CRD validation instead of expecting the controller that watches on the CRD to handle malformed objects. Otherwise the malformed objects can break all their consumers. I will close this issue and talk with VPC CNI if we can add validation. Please feel free to reopen it if feel necessary. Thanks.
