### ISSUE TITLE
Enable EKS Windows Support using the new VPC Resource Controller

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-resource-controller-k8s#4]
The newer version of VPC Controller has the support for managing IP Address for Windows Pods. However, the feature is not enabled yet. 

Need a migration strategy to migrate users from old VPC Resource Controller to the newer version of VPC Resource Controller which has significant performance improvements.

**Comment by iusergii** [comment]
@abhipth  I'm planning the onboarding of Windows Nodes and wonder if I can use it already.

**Comment by abhipth** [comment]
@iusergii we have not yet enabled the support using this controller. Currently the only way to enable windows support is to use the older controller on worker nodes [using the guide](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html)

**Comment by iusergii** [comment]
@abhipth  any plans to release this soon?

**Comment by abhipth** [comment]
@iusergii we are working on the release v1.1.0 which is planned for mid October.

**Comment by vmasule** [comment]
Hi @abhipth, Any chance this be released any time next week? We have go live scheduled in first week of November but before that impact of this new Controller need be tested out for any issues windows workloads we run.

**Comment by abhipth** [comment]
Windows Support is now available on EKS Control Plane. It is available on EKS Platform versions mentioned in [v1.1.0 release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0). Please feel free to re-open if you encounter any issues.

**Comment by vmasule** [comment]
Thanks for update. Actually we went live with older version will try this out later.
