### ISSUE TITLE
Why is taint preventing me from creating vpc.amazonaws.com/pod-eni capacity?

### ISSUE THREAD

**Issue by changhyuni** [aws/amazon-vpc-resource-controller-k8s#434]
**Describe the Bug**:
If the default node with the karpenter controller is tainted, the node created by karpenter will not have “vpc.amazonaws.com/pod-eni” in its capacity.

**Observed Behavior**:
`0/6 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 4 Insufficient vpc.amazonaws.com/pod-eni. preemption: 0/6`

**Environment**: EKS
- Kubernetes version (use `kubectl version`): 1.27
- CNI Version: v1.15.0
- OS (Linux/Windows): Linux

**Comment by sushrk** [comment]
Hi @changhyuni, can you provide more details on the issue? Is the security group for pods feature enabled in the cluster? Nodes by default are not tainted with resource `vpc.amazonaws.com/pod-eni` unless the feature is enabled. 

The controller updates the resource capacity on the node when the security group pods for feature is enabled, refer to workflow here https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/docs/sgp/workflow.md

**Comment by changhyuni** [comment]
@sushrk 
I'm sorry! 
I guess I reproduced it and the script is missing in userdata..!
