### ISSUE TITLE
Support Prefixes for Windows Worker Instances for Higher Pod Density

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-resource-controller-k8s#73]
**Is your feature request related to a problem? Please describe.**
Currently the number of Pods that can be scheduled on a Node is limited by the number of Secondary IPv4 Addresses on the Primary ENI. This limits the Pod density on the Windows Nodes.

With the feature of assigning a /28 prefix on a ENI, we can significantly increase the Pod Density for Nitro Based instances. For instance, the theoretical limit increase for `c5.large` changes from `9` ->  `/28 X 9 Prefixes` =  `144`

This would further reduce the number of calls to Assign/UnAssing IPv4 Addresses as the IP address allocation from a given Prefix can be done locally.

**Describe the solution you'd like**
- Support VPC Prefixes using the Primary ENI only for Nitro Instances.

**Comment by sushrk** [comment]
`v1.2.2` is now released with Windows PD support from EKS 1.25+, closing the issue.
