### ISSUE TITLE
Evaluate supporting Security Group for Pods for Windows Pod

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-resource-controller-k8s#74]
**Is your feature request related to a problem? Please describe.**
Security Group for Pods feature is only supported for Linux Pods. We need to consider if the feature is feasible and the scope of work for supporting the feature for Windows Pods. 

https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html

**Describe the solution you'd like**
Windows Pod should be able to use Security Groups per Pod.

**Comment by sushrk** [comment]
Closing this in favor of https://github.com/aws/containers-roadmap/issues/1083.
