### ISSUE TITLE
windows controller: unknown node

### ISSUE THREAD

**Issue by iusergii** [aws/amazon-vpc-resource-controller-k8s#77]
I'm observing a lot of error message in my **windows-vpc-resource-controller**:**v0.2.7** deployment and wondering if it has any impact to my cluster.

**Comment by abhipth** [comment]
@iusergii 1.1.0 will run on Control Plane and cannot be run on Data Plane. We are in the process of releasing it, will keep this thread updated as soon as the release is completed.

**Comment by abhipth** [comment]
@iusergii [v1.1.0](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0) is released. To migrate to the new controller you can follow this updated [guide](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html). Please do let us know if you encounter any issues with the new controller.
