### ISSUE TITLE
Update VPC Limits to match amazon-vpc-cni

### ISSUE THREAD

**Issue by bdwyertech** [aws/amazon-vpc-resource-controller-k8s#87]
The CNI added support for m6a, c6i and a few other instance types in `eni-max-pods.txt`
https://github.com/aws/amazon-vpc-cni-k8s/pull/1781

We reference the Limits map in `pkg/aws/vpc` in [aws/karpenter](https://github.com/aws/karpenter) to determine Branch ENI support, so these types are not taken into consideration for pods requiring `vpc.amazonaws.com/pod-eni`.

I see there is [another map within the CNI](https://github.com/martinpapez/amazon-vpc-cni-k8s/blob/01654383404fe88f18a89508d9406ad52c6eec1f/pkg/awsutils/vpc_ip_resource_limit.go) -- perhaps it should reference this repository.

**Comment by abhipth** [comment]
We are working on updating the Branch ENI limits for these new instance types and cut a new release. Will keep this thread posted as soon as I have update.

**Comment by haouc** [comment]
We have added and merged a few new instance types. Close this issue for now.
