### ISSUE TITLE
Additional ENI tag: Pod name

### ISSUE THREAD

**Issue by Vlaaaaaaad** [aws/amazon-vpc-resource-controller-k8s#88]
**What would you like to be enhanced**:
In addition to the current tags (`kubernetes.io/cluster/$NAME`, `eks:eni:owner`, `vpcresources.k8s.aws/vlan-id`, and `vpcresources.k8s.aws/trunk-eni-id`) I would like to see an additional `pod-name` tag attached to each ENI. 

**Why is the change needed and what use case will it solve**:
This will help with debugging and will lead to a slightly improved developer experience 🙂
I had to debug some complex Security Groups rules when using the Security-Groups-per-Pod feature, and getting the ENI used by a certain Pod was not as straightforward as it could be. I did most of my work in the AWS Console, but I was forced to use `kubectl` to get the pod's ENI (either by getting the Pod's IP and searching for that in the AWS Console or by doing a `kubectl describe pod` and getting the ENI ID from the events). Being able to stay in the AWS Console and filter the ENIs by a specific tag value would have made the process much easier.

---

Based on [a quick code reading](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/b91bd4f3925a21792bfee7876cf460884a5d2ea5/pkg/provider/branch/trunk/trunk.go#L330-L347), I am pretty sure this enhancement request should be here and not in [aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s), but I could be wrong. Apologies if that is the case!

**Comment by abhipth** [comment]
@Vlaaaaaaad In future if we decide to allocate Branch ENI to multiple Pods to increase Pod Density the tag based solution might not scale. We have a non public introspection API which has mapping of all the Pod UID (not the Pod Namespace/Name) -> ENI along with other information. [See](https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/62). Currently it's not available to users, but if this is something that could help enhance your debugging experience we can evaluate making this public.

**Comment by Vlaaaaaaad** [comment]
@abhipth that's a really good point and not something I even thought of! Yes, multiple Pods per ENI would totally run my proposal. And limiting this tag when only 1 Pod uses 1 ENI is... not great.

The non-public introspection API looks great, and integrating that with the AWS Console would be awesome (on the ENI page or, even better, on the EKS page where details are shown about a Pod)!

**Comment by haouc** [comment]
Closing this issue for now. Please feel free to re-open.
