### ISSUE TITLE
Branch network interfaces support for new generation instances

### ISSUE THREAD

**Issue by AhmadMS1988** [aws/amazon-vpc-resource-controller-k8s#97]
**What would you like to be added**:
Branch network interfaces support to enable Security groups for pods is not supported for new generation instance types like m6i, m6a, c6i, c6a, r6i and r6a.

**Why is this needed**:
This is needed to take advantage of the new instance types in Kubernetes in the case of security group for pods.

**Comment by AhmadMS1988** [comment]
@jayanthvn thank you for your response.
please correct me if I am wrong, but amazon-vpc-resource-controller-k8s is for windows nodes, and we use bottlerocket nodes. also we use vpc-cni add-on which is managed by EKS also, is it still relevant to forward the request to vpc-resource-controller-k8s repo?
Also based on EKS documentation [1], the instances are still not supported. the instances have been released since a while now, and we are prevented to take advantage of the performance uplift because we use security groups for pods.
I suggest to move the feature request back to amazon-vpc-cni-k8s or to amazon-vpc-cni-plugins if it is more relevent, but it has nothing to do with windows unless EKS control plane is windows based.
Thank you for your help.

[1] https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#supported-instance-types

**Comment by abhipth** [comment]
@AhmadMS1988 vpc-resource-controller manages Branch ENIs used by Pods using the Security Group for Pods feature as well. #95 should address the issue. However, I couldn't find r6a instance type in any public document.

**Comment by AhmadMS1988** [comment]
@abhipth , sorry, I just confirmed that there is no r6a, I was expecting it to be there when I wrote the request as m6a and c6a  as they use the same AMD CPU family.
So, is it supported now and can I launch the new instance types in my EKS cluster?
It is now running EKS 1.21 eks.4.

**Comment by abhipth** [comment]
@AhmadMS1988 controller is not released yet, we are planning to release it next week. This [post](https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/91#issuecomment-1055736081) can provide you with additional details.

**Comment by haouc** [comment]
A few new instance types were added and merged.
