### ISSUE TITLE
Reconcile Security Groups for Pods

### ISSUE THREAD

**Issue by ellistarn** [aws/amazon-vpc-resource-controller-k8s#99]
**Describe the Bug**:

When using Karpenter and SGP, pods are stuck in ContainerCreating for up to 30 minutes. https://github.com/aws/karpenter/issues/1252

**Observed Behavior**:
Security groups are only attached for pods that are bound after a Node is `Ready`. For pods that define `pod.spec.nodeName` or are bound by optimistic schedulers (e.g. Karpenter), the pod will remain stuck in Container Creating

**Expected Behavior**:
The VPC Resource Controller should trigger a reconciliation loop for all pods on a node when the node becomes ready. 

**How to reproduce it (as minimally and precisely as possible)**:
- https://karpenter.sh/v0.6.4/getting-started/
- Use the security group for pods feature
- Observe ContainerCreating

**Additional Context**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (Linux/Windows):

**Comment by haouc** [comment]
@ellistarn seems this is no longer an issue regarding the change in https://github.com/aws/karpenter/issues/1252 ? I am closing this issue for now. If this still need a fix in this controller, please feel free to reopen. Thanks

**Comment by ellistarn** [comment]
We ended up rearchitecting in a way that stopped this from happening. Still probably a useful resiliency feature for SGPP, but that's a judgement call for you folks.
